export const data = {
  categories: [
    { name: "articles-vedette", title: "Articles en vedette" },
    { name: "1achete-1offert", title: "1 acheté(s) = 1 offert(s)" },
    { name: "menus-burgers", title: "MENUS BURGERS 🍔+🍟+🥤" },
    { name: "nos-nouveautes", title: "NOS Nouveautés" },
    {
      name: "compose-ton-tacos",
      title: "COMPOSE TON TACOS 🌮 (seul ou en menu🍟+🥤)",
    },
    {
      name: "nos-tacos-signature",
      title: "NOS TACOS SIGNATURE 🌯👩🏻‍🍳 🌯 (seul ou menu🍟+🥤)",
    },
    {
      name: "nos-burgwichs",
      title: "NOS BURGWICHS 🌭 (SEUL OU EN MENU)",
    },
    { name: "petite-faim", title: "⚡️ PETITE FAIM ⚡️" },
    { name: "nos-menu-kids", title: "NOS MENU KIDS 🧒" },
    { name: "nos-boissons", title: "NOS BOISSONS 🥤" },
  ],

  supplements: [
    { name: "Œuf", price: 1.0 },
    { name: "Boursin", price: 1.0 },
    { name: "Cheddar", price: 1.0 },
    { name: "Raclette", price: 1.0 },
    { name: "Chèvre", price: 1.0 },
    { name: "Mozzarella", price: 1.0 },
    { name: "Poulet", price: 1.0 },
    { name: "Lardons", price: 2.0 },
    { name: "Jambon de dinde", price: 2.0 },
    { name: "Bacon", price: 2.0 },
  ],

  nbPieces: [
    { nb: 4, price: 0.0 },
    { nb: 6, price: 4 },
    { nb: 8, price: 3.7 },
    { nb: 12, price: 6.7 },
  ],

  boissons: [
    "Coca-Cola",
    "Coca-Cola Zero",
    "Fanta-orange",
    "Orangina",
    "Ice Tea",
    "Tropico",
    "Oasis-Tropical",
    "Eau",
  ],

  sauces: [
    "Mayonnaise",
    "Ketchup",
    "Blanche",
    "Hannibal",
    "Algérienne",
    "Barbecue",
    "Burger",
    "Harissa",
    "Andalouse",
    "Curry",
    "Poivre",
  ],

  saucesFromagere: ["Sans sauce", "Peu de sauce", "Avec sauce"],

  viandes: [
    "Escalope de poulet",
    "Nuggets",
    "Tenders",
    "Kebab",
    "Viande hachée",
    "Merguez",
    "Chicken curry",
  ],

  articles: [
    {
      id: "1",
      name: "Big Bacon Burger 🍔",
      slug: "big-bacon-burger",
      category: ["menus-burgers", "articles-vedette"],
      price: 14.9,
      image: "/images/big-bacon-burger.jpeg",
      description:
        "Pain bun, Triple Smashed Steak 🥩, Triple Cheddar 🧀, Sauce au choix, Bacon grillé 🥓, Salade 🥗, Tomate 🍅, Oignon caramélisé, Cornichons",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "2",
      name: "L'original Burger 🍔",
      slug: "loriginal-burger",
      category: ["menus-burgers", "articles-vedette"],
      price: 14.9,
      image: "/images/loriginal-burger.jpeg",
      description:
        "Pain bun, Triple Smashed Steak 🥩, Triple Cheddar 🧀, Sauce au choix, Bacon grillé 🥓, Salade 🥗, Tomate 🍅, Oignon caramélisé, Cornichons",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "3",
      name: "Double Cheese Burger 🍔",
      slug: "double-cheese-burger",
      category: ["menus-burgers", "articles-vedette"],
      price: 13.9,
      image: "/images/double-cheese-burger.jpeg",
      description:
        "Pain bun, Double Smashed Steak 🥩, Cheddar 🧀, Sauce au choix , Salade 🥗, Tomate🍅, Oignon blanc 🧅, Cornichons.",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "4",
      name: "Classic Burger 🍔",
      slug: "classic-burger",
      category: ["menus-burgers", "articles-vedette"],
      price: 12.9,
      image: "/images/classic-burger.jpeg",
      description:
        "Pain bun, Smash Steak 🥩, Cheddar 🧀, Sauce au choix, Oignon blanc 🧅, Cornichon. Servi avec des frites ultra croustillantes🍟, Boisson 🥤.",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "5",
      name: "Chicken Burger 🍔",
      slug: "chicken-burger",
      category: ["menus-burgers"],
      price: 12.9,
      image: "/images/chicken-burger.jpeg",
      description:
        "Pain bun, Crunchy chicken🍗, Cheddar🧀, Sauce au choix, Salade 🥗, Tomate 🍅, Oignon blanc 🧅, Cornichon.",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "6",
      name: "Chèvre Miel Burger 🍔🍯",
      slug: "chevre-miel-burger",
      category: ["menus-burgers", "articles-vedette"],
      price: 14.9,
      image: "/images/chevre-miel-burger.jpeg",
      description:
        "Pain bun, Double Smashed 🥩, Cheddar 🧀, Sauce au choix, Tomate 🍅 , Salade🥗, Oignon 🧅, Chèvre, Miel 🍯.",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "7",
      name: "Frenchy Burger 🍔",
      slug: "frenchy-burger",
      category: ["nos-nouveautes"],
      price: 14.5,
      image: "/images/frenchy-burger.jpeg",
      description:
        "Pain bun, Double Smashed Steak 🥩, Cheddar, Raclette , Sauce au choix, Galette pomme de terre , Salade 🥗, Tomate 🍅, Oignon , Cornichons",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "8",
      name: "L'oriental Burger 🍔",
      slug: "loriental-burger",
      category: ["nos-nouveautes"],
      price: 14.5,
      image: "/images/loriental-burger.jpeg",
      description:
        "Pain bun, Double Smashed Steak 🥩,Double Cheddar 🧀, Sauce au choix, Poivrons grillé, Chorizo, Salade 🥗, Tomate 🍅, Oignon , Cornichons.",
      sauces: true,
      boissons: true,
      supplements: true,
    },
    {
      id: "9",
      name: "A composer 3 viandes",
      slug: "a-composer-3-viandes",
      category: ["compose-ton-tacos", "articles-vedette"],
      price: 13.4,
      image: "/images/a-composer-3-viandes.jpeg",
      description:
        "🌯 Trois viandes au choix, garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      sauceFromagere: true,
      seulOuMenu: true,
      nbViandes: 3,
    },
    {
      id: "10",
      name: "A composer 2 viandes",
      slug: "a-composer-2-viandes",
      category: ["compose-ton-tacos", "articles-vedette"],
      price: 11.9,
      image: "/images/a-composer-2-viandes.jpeg",
      description:
        "🌯 Deux viandes au choix, garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: false,
      nbViandes: 2,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "11",
      name: "A composer 1 viandes",
      slug: "a-composer-1-viandes",
      category: ["compose-ton-tacos"],
      price: 9.9,
      image: "/images/a-composer-1-viandes.jpeg",
      description:
        "🌯 Deux viandes au choix, garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: false,
      nbViandes: 1,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "12",
      name: "Le Frenchy 🌯",
      slug: "le-frenchy",
      category: ["nos-tacos-signature"],
      price: 11.9,
      image: "/images/le-frenchy.jpeg",
      description:
        "Tortillas, Sauce aux choix, Cordon bleu, Raclette, lardons, Garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "13",
      name: "Le Chèvre Miel 🍯🌯",
      slug: "le-chevre-miel",
      category: ["nos-tacos-signature"],
      price: 11.9,
      image: "/images/le-chevre-miel.jpeg",
      description:
        "Tortillas, Sauce aux choix, Poulet Nature 🍗,Fromage de chèvre🐐, Miel🍯 Garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "14",
      name: "Le Texan 🌯",
      slug: "le-texan",
      category: ["nos-tacos-signature"],
      price: 11.9,
      image: "/images/le-texan.jpeg",
      description:
        "Tortillas, Sauce aux choix, Viande Hachée, Cheddar🧀, Bacon🥓 Garni d'une sauce fromagère maison et de frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "15",
      name: "L'oriental 🌯",
      slug: "loriental",
      category: ["nos-tacos-signature"],
      price: 11.9,
      image: "/images/loriental.jpeg",
      description:
        "Tortillas, Sauce aux choix, Viande hachée , Merguez, Poivrons Grillé Garni d'une sauce fromagère maison et des frites. 🍟 🥤 Seul ou en Menu.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: true,
      seulOuMenu: true,
    },
    {
      id: "16",
      name: "Américain Burgwich",
      slug: "americain-burgwich",
      category: ["nos-burgwichs", "articles-vedette"],
      price: 10.5,
      image: "/images/americain-burgwich.jpeg",
      description:
        "Pain brioché, Steak maison 🥩, Cheddar 🧀, Œuf, Sauce au choix, Salade 🥗, Tomate 🍅, Oignon frie, Cornichons.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: false,
      seulOuMenu: true,
    },
    {
      id: "17",
      name: "L'oriental Burgwich",
      slug: "loriental-burgwich",
      category: ["nos-burgwichs", "articles-vedette"],
      price: 10.9,
      image: "/images/loriental-burgwich.jpeg",
      description:
        "Pain brioché, Steak maison, Cheddar🧀,chorizo, Poivron, Sauce au choix, Salade 🥗, Tomate 🍅, Oignon 🧅.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: false,
      seulOuMenu: true,
    },
    {
      id: "18",
      name: "Chèvre Miel Burgwich 🍯",
      slug: "chevre-miel-burgwich",
      category: ["nos-burgwichs"],
      price: 10.5,
      image: "/images/chevre-miel-burgwich.jpeg",
      description:
        "Pain brioché, steak haché , Sauce au choix, Tomate 🍅 , Salade🥗, Oignon 🧅, Chèvre, Miel 🍯.",
      sauces: true,
      boissons: false,
      supplements: true,
      sauceFromagere: false,
      seulOuMenu: true,
    },
    {
      id: "19",
      name: "Box Nugetts",
      slug: "box-nugetts",
      category: ["petite-faim", "articles-vedette", "1achete-1offert"],
      price: 5.5,
      image: "/images/box-nugetts.jpeg",
      description: "4 pièces",
      sauces: true,
      boissons: false,
      supplements: false,
      sauceFromagere: false,
      seulOuMenu: false,
    },

    {
      id: "20",
      name: "Box Mozza Stick",
      slug: "box-mozza-stick",
      category: ["petite-faim"],
      price: 4.9,
      image: "/images/box-mozza-stick.jpeg",
      description: "4 pièces de Mozza sticks croustillante 😋",
      sauces: true,
      boissons: false,
      supplements: false,
      sauceFromagere: false,
      seulOuMenu: false,
      nbPieces: true,
    },
    {
      id: "21",
      name: "Frites 🍟",
      slug: "frites",
      category: ["petite-faim"],
      price: 3.5,
      image: "/images/frites.jpeg",
      description: "Frites croustillantes.",
      boissons: false,
      supplements: false,
      sauceFromagere: false,
      seulOuMenu: false,
    },
    {
      id: "22",
      name: "Cheese Oeuf Burger 🧀 🍔",
      slug: "cheese-oeuf-burger",
      category: ["petite-faim"],
      price: 5.9,
      image: "/images/cheese-oeuf-burger.jpeg",
      description: "Pain bun, Cheddar 🧀, Oeuf, Sauce Classic , Cornichons.",
      boissons: false,
      supplements: false,
      sauceFromagere: false,
      seulOuMenu: false,
    },
    {
      id: "23",
      name: "Box Tenders 🐓",
      slug: "box-tenders",
      category: ["petite-faim"],
      price: 5.9,
      image: "/images/box-tenders.jpeg",
      description: "3 pièces blanc de poulet crispy.",
      sauces: true,
      boissons: false,
      supplements: false,
      sauceFromagere: false,
      seulOuMenu: false,
      nbPieces: [{ nb: 3, price: "", nb: 6, price: 4 }],
    },

    {
      id: "24",
      name: "Double Cheese Burger 🍔",
      slug: "double-cheese-burger-seul",
      category: ["petite-faim"],
      price: 9.9,
      image: "/images/double-cheese-burger-seul.jpeg",
      description:
        "Pain bun, Double Smash Steak 🥩, Cheddar 🧀, Sauce au choix, Oignon blanc 🧅, Cornichon.",
      sauces: true,
      supplements: true,
    },
    {
      id: "25",
      name: "Classic Burger 🍔",
      slug: "classic-burger-seul",
      category: ["petite-faim"],
      price: 8.9,
      image: "/images/classic-burger-seul.jpeg",
      description:
        "Pain bun, Smashed Steak 🥩, Cheddar 🧀, Sauce au choix , Salade 🥗, Tomate🍅, Oignon blanc 🧅, Cornichons.",
      sauces: true,
      supplements: true,
    },
    {
      id: "26",
      name: "Menu kids burger",
      slug: "menu-kids-burger",
      category: ["nos-menu-kids"],
      price: 8.9,
      image: "/images/menu-kids-burger.jpeg",
      description: "Cheese burger, petite frite, capri sun",
    },
    {
      id: "27",
      name: "Menu kids Nuggets",
      slug: "menu-kids-nuggets",
      category: ["nos-menu-kids"],
      price: 8.9,
      image: "/images/menu-kids-nuggets.jpeg",
      description: "6 Nuggets, petite frite, capri sun",
    },
    {
      id: "28",
      name: "Coca-cola",
      slug: "coca-cola",
      category: ["nos-boissons"],
      price: 2.0,
      image: "/images/coca-cola.jpeg",
      description: "Canette 33cl",
    },
    {
      id: "29",
      name: "Oasis Tropical",
      slug: "oasis-tropical",
      category: ["nos-boissons"],
      price: 2.0,
      image: "/images/oasis-tropical.jpeg",
      description: "Canette 33cl",
    },
    {
      id: "30",
      name: "Tropico",
      slug: "tropico",
      category: ["nos-boissons"],
      price: 1.55,
      image: "/images/tropico.jpeg",
      description: "Canette 33cl",
    },
    {
      id: "31",
      name: "Coca-cola Zéro",
      slug: "coca-cola-zero",
      category: ["nos-boissons"],
      price: 2,
      image: "/images/coca-cola-zero.jpeg",
      description: "Canette 33cl",
    },
    {
      id: "32",
      name: "Orangina",
      slug: "orangina",
      category: ["nos-boissons"],
      price: 2,
      image: "/images/orangina.jpeg",
      description: "Canette 33cl",
    },
    {
      id: "33",
      name: "Fanta orange",
      slug: "fanta-orange",
      category: ["nos-boissons"],
      price: 1.55,
      image: "/images/fanta-orange.jpeg",
      description: "Canette 33cl",
    },
  ],
};
